config/routes.rb
Rails.application.routes.draw do
  root :to => 'root#redirection_principal'

  namespace :application do
    get 'principal'
    get 'resume'
    get '/:id', action: 'detail'
  end
  namespace :familles do
    post 'resume_famille'
    post 'create_parent'
    post 'create_enfant'
    post 'familles'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enfant.rb
class Enfant < ApplicationRecord
  belongs_to :parents, optional: true
end

app/models/famille.rb
class Famille < ApplicationRecord
  has_one :parents
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :famille, optional: true
  has_many :enfants, inverse_of: :parent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :principal

  def principal
    @parent = Parent.new
    @enfant = Enfant.new
    @famille = list_famille
    @info_enfant = Enfant.where(parent_id: @parent_id) if !@parent_id.nil?
  end

  def list_famille
    Famille.all
  end

  def detail
    @famille = Famille.find(params[:id])
    @parents = Parent.where(famille_id: @famille.id) if @famille.present?
    @enfants = Enfant.where(parent_id: @parents.ids) if @parents.present?
    puts 'hello'
    puts @famille.inspect
    puts @parents.inspect
    puts @enfants.inspect
  end
end

app/controllers/familles_controller.rb
class FamillesController < ActionController::Base
  before_action :principal

  def principal
    @parent = Parent.new
    @enfant = Enfant.new
    @famille = list_famille
  end

  def resume_famille
    redirect_to application_resume_path(:id => params[:id])
  end

  def create_parent
    @parent = Parent.last
    @parent.update(parent_params)
    @parent.save!

    flash.notice = "Création des parents avec succès."
    redirect_to application_principal_path
  end

  def familles
    @parent.update(famille_id: params[:parent][:famille_id])
    @parent.save
    flash.notice = "Enregistrement du nom de famille avec succès."
    redirect_to application_principal_path
  end

  def create_enfant
    parent_id = Parent.last.id
    @enfant.update(enfant_params(parent_id))
    @enfant.save!
    flash.notice = "Création de l'enfant avec succès."
    redirect_to application_principal_path
  end

  def list_famille
    Famille.all
  end

  def parent_params
    params.require(:parent).permit(:prenom_pere, :annee_naissance_pere, :prenom_mere, :annee_naissance_mere)
  end

  def enfant_params(parent_id)
    permited_params = params.require(:enfant).permit(:prenom, :annee_naissance)
    permited_params[:parent_id] = parent_id
    permited_params
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  include ApplicationHelper

  def index
  end

  def redirection_principal
    redirect_to application_principal_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level, sticky: false, fixed: false)
    class_names = case level
    when 'notice'
      ['alert-success']
    when 'alert'
      ['alert-danger']
    when 'timedout'
      ['alert-danger']
    end
    if sticky
      class_names << 'sticky'
    end
    if fixed
      class_names << 'alert-fixed'
    end
    class_names.join(' ')
    end
end

app/views/application/detail.html.haml
.dossiers-headers.sub-header
  .container
    %h1.page-title Famille #{@famille.nom}

.container
  - if @parents.present?
    %h1.tab-title Les parents
    %table.table.dossiers-table.hoverable
      %thead
        %tr
          %th Prénom du père
          %th Date de naissance
          %th Prénom de la mère
          %th Date de naissance
        %tbody
          - @parents.each do |parent|
            %tr
              %td
                = parent.prenom_pere
              %td
                = parent.annee_naissance_pere
              %td
                = parent.prenom_mere
              %td
                = parent.annee_naissance_mere

    %br
    %br
    %br
    %h1.tab-title Les enfants
    %table.table.dossiers-table.hoverable
      %thead
        %tr
          %th Prénom 
          %th Date de naissance
        %tbody
          - @enfants.each do |enfant|
            %tr
              %td
                = enfant.prenom
              %td
                = enfant.annee_naissance
  - else
    %br
    %h1.tab-title Pas de données
    %br
      = image_tag 'yoda.png', alt: 'Yoda'

app/views/application/principal.html.haml
.dossiers-headers.sub-header
  .container
    %h1.page-title Ajouter une Famille

.dossier-edit.container
  = form_for @parent,
    url: familles_familles_path,
    multipart: true,
    html: { class: 'form' } do |f|
    = f.label :nom_famille_id do
      Nom de famille
      = f.select :famille_id,
       @famille.map { |number| [number.nom, number.id]},
       {include_blank: true},
        required: true
    
    .text-right
      = f.button 'Enregistrer', class: 'button primary send'

  = form_for @parent,
    url: familles_create_parent_path(@famille),
    html: { class: 'form' } do |f|
    .editable-champ.editable-champ-repetition
      %h3.header-subsection Les parents
      %div{ class: "row row" }
        %div{ class: "repetition-#{f.index}" }
          %h3.header-subsection Père
          %div{ class: "row row" }
            = f.label :prenom_pere do
              Prénom
              = f.text_field :prenom_pere, placeholder: 'Prénom du père', required: true

              = f.label :annee_naissance_pere do
                Date de naissance
                = f.date_field :annee_naissance_pere,
                  placeholder: 'aaaa-mm-jj'
        
        %div{ class: "repetition-#{f.index}" }
          %h3.header-subsection Mère
          %div{ class: "row row" }
            = f.label :prenom_mere do
              Prénom
              = f.text_field :prenom_mere, placeholder: 'Prénom de la mère', required: true

              = f.label :annee_naissance_mere do
                Date de naissance
                = f.date_field :annee_naissance_mere,
                  placeholder: 'aaaa-mm-jj'

        .text-right
          = f.button 'Enregistrer', class: 'button primary send'

  = form_for @enfant,
    url: familles_create_enfant_path(@famille),
    html: { class: 'form' } do |f|
    .editable-champ.editable-champ-repetition
      %h3.header-subsection Les enfants
      %div{ class: "row row" }
        %div{ class: "repetition-#{f.index}" }
          = f.label :prenom do
            Prénom
            = f.text_field :prenom, placeholder: 'Prénom de l\'enfant', required: true

            = f.label :annee_naissance do
              Date de naissance
              = f.date_field :annee_naissance,
                placeholder: 'aaaa-mm-jj'

        .text-right
          = f.button 'Enregistrer', class: 'button primary send'

app/views/application/resume.html.haml
.dossiers-headers.sub-header
  .container
    %h1.page-title Les familles

.container
  %table.table.dossiers-table.hoverable
    %thead
      %tr
        %th.number-col Identifiant
        %th Nom
      %tbody
        - @famille.each do |famille|
          %tr{ data: { 'dossier-id': famille.id } }
            %td.number-col
              = link_to(application_path(famille.id), class: 'cell-link', tabindex: -1) do
                = famille.id
            %td
              = famille.nom

app/views/layouts/_flash_messages.html.haml
#flash_messages
  - if flash.any?
    #flash_message.center
      - flash.each do |key, value|
        - sticky = defined?(sticky) ? sticky : false
        - fixed = defined?(fixed) ? fixed : false
        - if key != 'timedout'
          - if value.class == Array
            .alert{ class: flash_class(key, sticky: sticky, fixed: fixed) }
              - value.each do |message|
                = sanitize(message)
                %br
          - else
            .alert{ class: flash_class(key, sticky: sticky, fixed: fixed) }
              = sanitize(value)

app/views/layouts/_footer.html.haml
#footer
  %p{ class: "copyright col-md-push-#{12-main_container_size} col-md-#{main_container_size} col-lg-push-#{12-main_container_size} col-lg-#{main_container_size} text-muted small" }
    = link_to 'DINUM', 'https://www.numerique.gouv.fr/dinum/'
    = Time.zone.now.year
    \-
    = link_to 'Nouveautés', DOC_NOUVEAUTES_URL, target: '_blank'
    \-
    = link_to 'Statistiques', stats_path
    \-
    = link_to 'CGU / Mentions légales', CGU_URL, target: '_blank'
    \-
    = link_to 'Documentation', DOC_URL, target: '_blank'
    \-
    = link_to 'FAQ', FAQ_ADMIN_URL, target: '_blank'
    \-
    = link_to 'Inscription ateliers en ligne', WEBINAIRE_URL, target: '_blank'
  %p
    = "Version: " + DS_MINARM_VERSION

app/views/layouts/_main_container.html.haml
#main-container{ class: "col-xs-#{main_container_size}" }
  .row
    = render partial: 'layouts/flash_messages'
  .row
    = yield
  .row

app/views/layouts/_navbar.html.haml
.col-xs-2
  %a#title-navbar{ href: root_path }
    .row#home
      .col-lg-5.no-padding
        = image_tag('marianne.svg', class: 'logo')
      .col-lg-6.no-padding#tps-title
        = APPLICATION_NAME

.col-xs-10.no-padding
  #navbar-body
    .row
      %div{ style: "max-width: 50%; position: absolute; display: flex; flex-direction: column; justify-content: center; height: 60px; line-height: 20px; z-index: 2;" }
        %span
          👉 Besoin d’aide ? Consultez <a target="_blank" rel="noopener" href="#{DOC_URL}">la documentation</a> et <a target="_blank" rel="noopener" href="#{FAQ_URL}">l’aide</a>, contactez-nous par <a style="cursor:hand" onclick="$crisp.push(['do', 'chat:open'])">chat</a> ou <a href="#{contact_admin_path}" target="_blank" rel="noopener">email</a>, ou <a target="_blank" rel="noopener" href="#{CALENDLY_URL}">prenez RDV</a>.
      -# BEST WTF EVER
      -# this begin rescue hides potentials bugs by displaying another navbar
      - begin
        = render partial: @navbar_url
      - rescue
        = render partial: 'layouts/navbars/navbar_default'

      = render partial: 'layouts/navbars/navbar_log_options'

app/views/layouts/_new_header.haml
%header.new-header{ class: "new-header-with-border", role: 'banner' }
  .header-inner-content

    .flex.align-center.justify-center
      = link_to application_principal_path, class: 'header-logo justify-center', title: "Test" do
        .mr-20
          = image_tag 'starwars.svg', alt: 'Star wars', width: '65'
        .mr-40
          %span.big.site-title>
            = APPLICATION_NAME
          %span.small.site-title>
            = APPLICATION_SHORTNAME
      
      %ul.header-tabs
        %li
          = active_link_to application_principal_path, active: :inclusive, class: 'tab-link' do
            Saisie d'une famille
        %li
          = active_link_to application_resume_path , active: :inclusive, class: 'tab-link' do
            Liste des familles

app/views/layouts/application.html.haml
!!! 5
%html{ lang: "fr", class: yield(:root_class) }
  %head
    %meta{ "http-equiv": "Content-Type", content: "text/html; charset=UTF-8" }
    %meta{ "http-equiv": "X-UA-Compatible", content: "IE=edge" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    = csrf_meta_tags

    %title
      = content_for?(:title) ? "#{yield(:title)} · #{APPLICATION_NAME}" : APPLICATION_NAME

    = favicon_link_tag(image_url("favicons/favicon.png"), type: "image/png")

    = stylesheet_link_tag 'new_design/new_application', media: 'all'
    = stylesheet_link_tag 'new_design/print', media: 'print'

    = Gon::Base.render_data(camel_case: true, init: true, nonce:  request.content_security_policy_nonce)

  %body{ id: content_for(:page_id), class: browser.platform.ios? ? 'ios' : nil }
    .page-wrapper
      = render partial: "layouts/new_header"
      %main
        = render partial: "layouts/flash_messages"
        = content_for?(:content) ? yield(:content) : yield

      - if content_for?(:footer)
        = content_for(:footer)

      = yield :charts_js